[build]
command = "npx vite build"
publish = "dist"

[[redirects]]
  from = "/cars-data.xml"
  to = "/.netlify/functions/cars-data"
  status = 200

[[redirects]]
  from = "/share"
  to = "/.netlify/functions/share"
  status = 200

[[redirects]]
  from = "/img-proxy.php"
  to = "https://vmi2357520.contaboserver.net/img-proxy.php"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200